const fs = require('node:fs'),
  path = require('node:path'),
  crypto = require('node:crypto'),
  ts = require('typescript')
require.extensions['.ts'] = (m, p) =>
  m._compile(
    ts.transpileModule(fs.readFileSync(p, 'utf8'), {
      compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
    }).outputText,
    p
  )
const { SORTING_ALGORITHMS, SORTING_CODE } = require('../src/lib/sortingAlgorithms.ts')
const contents = SORTING_ALGORITHMS.map(a => [
  a.id,
  fs.readFileSync(`src/app/sorting/_content/${a.id}.md`, 'utf8'),
])
const hash = crypto
  .createHash('sha256')
  .update(fs.readFileSync('src/lib/sortingAlgorithms.ts'))
  .update(JSON.stringify(contents))
  .digest('hex')
const version = `sorting-${hash.slice(0, 12)}`
const artifacts = {
  'src/lib/courseVersion.ts': `// Generated by npm run course:build; checked in CI.\nexport const COURSE_VERSION = '${version}'\n`,
}
const documents = SORTING_ALGORITHMS.map(a => {
  const name = `sorting-${a.id}.md`,
    content =
      contents.find(([id]) => id === a.id)[1] +
      `\n\n## 本平台交互演示的确切变体\n\n课程版本：${version}。比较只统计数值之间的比较；交换仅统计两个不同位置的交换；写入只统计写回主数组（含归并剩余复制），辅助缓冲区构造另计。初始状态不属于执行步骤。\n\n本页 ${a.name}：最佳 ${a.timeComplexity.best}、平均 ${a.timeComplexity.average}、最坏 ${a.timeComplexity.worst}；空间 ${a.spaceComplexity}；${a.stability}。展示引擎存储步骤快照的开销另计，不包含在算法本身复杂度中。\n\n以下代码与动画事件的行映射一致，swap 表示交换两个不同位置；实际元素同时保留原始身份。\n\n\`\`\`javascript\n${SORTING_CODE[a.id]}\n\`\`\`\n`
  artifacts[`course-release/${name}`] = content
  return {
    algorithmId: a.id,
    name,
    version,
    bizTag: `sorting:${a.id}`,
    sourceType: 'course',
    sha256: crypto.createHash('sha256').update(content).digest('hex'),
  }
})
artifacts['course-release/manifest.json'] =
  JSON.stringify({ version, sourceHash: hash, documents }, null, 2) + '\n'
artifacts['course-release/golden-questions.json'] =
  JSON.stringify(
    {
      version,
      cases: [
        ['bubble', '为什么有序输入只比较 n-1 次？', '一轮无交换提前结束'],
        ['insertion', '左侧前缀有序是否说明元素都已归位？', '后续插入可能继续移动'],
        ['merge', '为什么相等时先取左侧？剩余复制计比较吗？', '稳定性；剩余复制只计写入'],
        ['quick', '有序输入的最坏时间和栈空间？', 'O(n²) 和 O(n)'],
        ['shell', '本页使用什么增量？平均复杂度可否套用其他序列？', '折半增量；不能'],
        ['heap', '取出堆顶后已归位尾部是否继续堆化？', '仅修复缩小后的有效堆'],
        ['radix', '能否悄悄把负数或小数变为整数再排序？', '拒绝非法输入；不改变问题'],
        ['selection', '交换最小值是否可能改变相等元素的相对顺序？', '可能，因此不稳定'],
      ].map(([algorithmId, question, expectedAnswer]) => ({
        algorithmId,
        question,
        expectedAnswer,
        expectedVersion: version,
        expectedDocument: `sorting-${algorithmId}.md`,
      })),
    },
    null,
    2
  ) + '\n'
let failed = false
for (const [file, content] of Object.entries(artifacts))
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) {
      console.error(`stale: ${file}`)
      failed = true
    }
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true })
    fs.writeFileSync(file, content)
  }
if (failed) process.exitCode = 1
else console.log(`${version}: ${documents.length} course documents verified`)
